mongodb:
    url: mongodb://localhost:27017/
    database: hatemap
    collection: tweets2
tagme:
    token: 7f5391f2-142e-4fd5-9cc9-56e91c4c9add-843339462
    lang: it
    is_twitter: True
    rho_value: 0.15
twitter:
    configuration:
        barer_token: AAAAAAAAAAAAAAAAAAAAAAPtPgEAAAAAoVlZ4I0szkcu4dL%2Bhqif%2F%2BF45Oo%3DJbvSo773bskLu1GexDv9Dq1HjuSjfSwfxgLdDXEdlPO5mKyE6G
        end_point: https://api.twitter.com/2/tweets/search/all
    search:
        # MANDATORY:
        # Please fill at least one of the following fields. If both fields are set it's possible to search for a twitter with the given keyword tweeted by the specific user.

        # enter the keyword/s to search for on twitter. It's also possible use logical operators. If no logical operator are specified all keywords will be searched in AND.
        # the AND operator is handle by a space, so to search "Joe AND Trump" just write "Joe Trump", the OR operator is "OR".
        # for example: "Joe Biden", "Biden OR Trump", "(Biden OR Trump) whitehouse" (the last query means: "(Biden OR Trump) AND whitehouse").
        keyword: sole

        # enter the username or the user id to search for tweets of a specific user.
        user:

        #OPTIONAL:
        # the language of the tweets
        lang: it

        # enable/disbale the twitter context annotation in the twitter response
        context_annotations: True

        # the max results of tweets for the first page
        n_results: 500

        # geo parameter.
        # only one of the following fields could be set
        geo:
            place:
            place_country: IT
            # example value: -105.301758 39.964069 -105.178505 40.09455
            bounding_box:
            # please if you want search by point radius set all the parameters in the point_radius section.
            point_radius:
                # example value: 2.355128
                longitude:
                # 48.861118
                latitude:
                # 16km
                radius:


