mongodb:
    url: mongodb://localhost:27017/
    database: hatemap
    collection: all_tweets4
#possible values: extract delete
mode: extract
#json or csv (only with extract mode)
format: csv
criteria:
  #possible values: negative positive neutral
  sentiment:
  #a list of keywords separated by a comma
  keywords:
  #
  postag: ADV
  #a raw NoSql query
  raw_query: